[project]
name = "encodex"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyfiglet>=1.0.2",
]

[dependency-groups]
dev = [
    "ruff>=0.11.4",
]

[tool.ruff.lint.pydocstyle]
convention = "google"
